### ISSUE TITLE
Compilation failure on auto generated fabric builder class, Method not found

### ISSUE THREAD

**Issue by ekowsal** [fabric8io/kubernetes-client#6724]
### Describe the bug

I am generating custom crd generator with help io.strimzi.api, and fabric8 api.

```
Buildable(
        editableEnabled = false,
        builderPackage = Constants.FABRIC8_KUBERNETES_API,
        refs = {@BuildableReference(CustomResource.class)}
)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"apiVersion", "kind", "metadata", "spec", "status"})
@Group(MessageBus.RESOURCE_GROUP)
@Version(MessageBus.V1)
@EqualsAndHashCode(callSuper = true)
public class MessageBus extends CustomResource<MessageBusKFSpec, MessageBusKFStatus> implements Namespaced  {
```

There is maven compilation error like below for auto generated source.

```
operator/target/generated-sources/annotations/io/strimzi/operator/frontend/MessageBusBuilder.java:[54,33] cannot find symbol
  symbol:   method getMetadata()
  location: variable fluent of type io.strimzi.operator.frontend.MessageBusFluent<?>
```
  
  It is coming after updating fabric8 api from 6.7.2 to 6.9.2.
  
  The same logic works in strimzi 0.39.0
  
  https://github.com/strimzi/strimzi-kafka-operator/blob/main/api/src/main/java/io/strimzi/api/kafka/model/mirrormaker2/KafkaMirrorMaker2.java

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

I am generating custom crd generator with help io.strimzi.api, fabric8 api.

```
Buildable(
        editableEnabled = false,
        builderPackage = Constants.FABRIC8_KUBERNETES_API,
        refs = {@BuildableReference(CustomResource.class)}
)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"apiVersion", "kind", "metadata", "spec", "status"})
@Group(MessageBus.RESOURCE_GROUP)
@Version(MessageBus.V1)
@EqualsAndHashCode(callSuper = true)
public class MessageBus extends CustomResource<MessageBusKFSpec, MessageBusKFStatus> implements Namespaced  {
```

There is maven compilation like below for auto generated source.

```
operator/target/generated-sources/annotations/io/strimzi/operator/frontend/MessageBusBuilder.java:[54,33] cannot find symbol
  symbol:   method getMetadata()
  location: variable fluent of type io.strimzi.operator.frontend.MessageBusFluent<?>
```

### Expected behavior

There should be any compilation failure

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
operator/target/generated-sources/annotations/io/strimzi/operator/frontend/MessageBusBuilder.java:[54,33] cannot find symbol
  symbol:   method getMetadata()
  location: variable fluent of type io.strimzi.operator.frontend.MessageBusFluent<?>
```

**Comment by ekowsal** [comment]
It is in my project, not in strimzi. Yes generating class from CRD
 I am using strimzi used version only. Also using same sundrio version well

**Comment by manusa** [comment]
can you please create a small reproducer?

**Comment by ekowsal** [comment]
After adding @BuildableReference(io.fabric8.kubernetes.api.model.ObjectMeta.class) in buildable annotations, it is worked. We can close the issue.
