### ISSUE TITLE
KubernetesClientException: JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency.

### ISSUE THREAD

**Issue by PulLa1** [fabric8io/kubernetes-client#4251]
### Describe the bug

Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath.
	at io.fabric8.kubernetes.client.internal.CertUtils.handleECKey(CertUtils.java:164)
	at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:134)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:112)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:247)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:153)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:147)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:204)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory.createHttpClient(OkHttpClientFactory.java:89)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:164)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:48)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:40)
	at io.fabric8.kubernetes.client.BaseKubernetesClient.<init>(BaseKubernetesClient.java:151)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:34)
	at com.yz.zk.K8sDemo.main(K8sDemo.java:17)

### Fabric8 Kubernetes Client version

5.12.2

### Steps to reproduce

I try to connect k3s by kubeconfig。
this is my kubectl command:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/27192614/177314366-5e728f8a-4336-4bb4-9454-a785387acdfa.png">

### Expected behavior

public class K8sDemo {

    public static void main(String[] args) {
        System.setProperty(Config.KUBERNETES_KUBECONFIG_FILE, "/myroot/.kube/k3s.yaml");
        DefaultKubernetesClient client = new DefaultKubernetesClient();
    }
}

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

macOS

**Comment by PulLa1** [comment]
Ok I found the bug：java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
append maven to solve the problem：

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.59</version>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.59</version>
        </dependency>

**Comment by rohanKanojia** [comment]
We need to add documentation about it. There is a pull request open that adds an FAQ about it https://github.com/fabric8io/kubernetes-client/pull/4237 .

Could you please review this and see if it's okay?

**Comment by martinwunderlich-celonis** [comment]
Hello, sorry for posting to the closed issue, but I have a related problem: Is there a way to use the fabric8 Kubernetes Client without BouncyCastle? I'm getting the following error: 

`io.fabric8.kubernetes.client.KubernetesClientException: JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath.`

Due to restrictions in my project, I cannot add BC as a direct dependency.

**Comment by shawkins** [comment]
@martinwunderlich-celonis see #6008

**Comment by martinwunderlich-celonis** [comment]
@shawkins Thanks again. I am happy to confirm that removing the Bouncycastle library works when I upgrade the fabric8 client from 6.13.1 to 7.0-SNAPSHOT (built locally).
